### ISSUE TITLE
Rolling with advantage/disadvantage shows empty fields

### ISSUE THREAD

**Issue by vegichan** [arkie/dicebot#40]
/roll d20k-5

> Dicebot APP [6:48 PM]
> @Vegi rolled *20*
> Dice
> 1d20
> Rolls
> 20
> Keep
> -1
> Removed

The removed field is always empty.

**Comment by arkie** [comment]
I'm not sure what you're expecting from `/roll d20k-5` - that should translate as roll one dice, and keep the lowest five results (so none are removed)

`/roll 2d20k1` would be the more standard roll two dice and take the highest.

Let me know if that doesn't make sense?
