### ISSUE TITLE
Afford use of all operators in conjunction with `for`?

### ISSUE THREAD

**Issue by jg-made** [arkie/dicebot#46]
When I do:
```
/roll 1d3 for foo, + 1d3 for bar
```
I get the both results added.

When I do:
```
/roll 1d3 for foo, + 1d3 for bar
```
I get the both results subtracted.

But when I do:
```
/roll 1d3 for foo, ^ 1d3 for bar
```
I get the both results added. I would like to see the maximum. Is it possible to do this?

**Comment by arkie** [comment]
`for` is currently the last thing applied, so would likely be fairly complicated to allow it to intersperse between other operators - `/roll 1d3 ^ 1d3 for foo` should work for the max of the two rolls, but there's not a good way to have it answer with a label.

**Comment by jg-made** [comment]
That's OK. Thanks anyway. I will close this since it is more of a question than an issue.
