### ISSUE TITLE
roll.go is missing rand.Seed initialization

### ISSUE THREAD

**Issue by sztrzask** [arkie/dicebot#50]
Hi, 

I've noticed that rolls doesn't seem random.

I've checked `roll.go` file and I've noticed that you're missing `Seed` call? Apparently you should seed `rand` to minimize sequence and pattern occurrences .

Reference https://stackoverflow.com/questions/39529364/go-rand-intn-same-number-value

**Comment by arkie** [comment]
It's currently Seed with the time during each call, I believe -https://github.com/arkie/dicebot/blob/master/roll.go#L187

Let me know if it seems like that's not actually taking affect due to being outside the package, however.

**Comment by sztrzask** [comment]
Cool. Do you happen to know if slack provides correct `time.Now()` for go or is it "frozen" like in go playground?

**Comment by arkie** [comment]
`time.Now` is actually evaluated on the server running the bot (i.e. in App Engine), Slack just triggers the request.
