### ISSUE TITLE
`1 - 1 = -2`

### ISSUE THREAD

**Issue by eriksw** [arkie/dicebot#51]
This input `/roll -1d-1` results in:

    [user] rolled *1* - *1* = *-2*

Yes, it's a nonsense input, but it's a bit silly that the output can be a mathematically invalid expression.

**Comment by JShillin** [comment]
Looks like you have written -(1d)-1 so its actually -1 - 1 = -2

**Comment by arkie** [comment]
As explained by @JShillin, closing out as working as intended 👍
