### ISSUE TITLE
Greater Than/Less Than? 

### ISSUE THREAD

**Issue by jstillwa** [arkie/dicebot#60]
![Screen Shot 2020-06-04 at 9 20 46 AM](https://user-images.githubusercontent.com/3878860/83782624-c0272800-a644-11ea-911a-2af4f15d911a.png)

The <> don't see to be working?

**Comment by arkie** [comment]
The current parsing splits on space IIRC, which is likely the issue you're seeing (and is a larger change to fix heh).

<img width="396" alt="Screen Shot 2020-06-04 at 14 28 34" src="https://user-images.githubusercontent.com/232986/83796859-af3fdc00-a66f-11ea-9c6d-241f935d2d11.png">

Re-open if you're still seeing without the space!
