### ISSUE TITLE
Thread roll

### ISSUE THREAD

**Issue by elafontaine** [arkie/dicebot#61]
Could the dicer bot make the roll in  threads ?  This would allow for clean sub-conversation rolls as well .

ie.

in a thread, `/roll 2d6`

**Comment by arkie** [comment]
I'd be happy to support this, but unfortunately Slack's documentation is extremely poor - this [medium](https://medium.com/slack-developer-blog/bringing-your-bot-into-threaded-messages-cd272a42924f) article (nominally from Slack) suggests that it's a possibility, but Slack's [command documentation](https://api.slack.com/interactivity/slash-commands) makes no mention of what `permission to read and write messages` actually maps to within the new OAuth infrastructure.

I tried the shotgun approach of adding several related permissions to the app for testing, but couldn't get it to respond with anything other than the following error 🙄 
<img width="343" alt="Screen Shot 2020-07-08 at 01 04 45" src="https://user-images.githubusercontent.com/232986/86878501-072a9200-c0b7-11ea-92cc-69b1e73340ff.png">

If you can find anything more useful, or can get it working within a test instance, I'd also be happy to accept a PR.

**Comment by watson13j** [comment]
I submitted a PR for this. I have zero experience writing slack bots, but it looks like all you need is to grab thread_ts from the message and make sure the response contains the same thread_ts payload. 🤷‍♂️

**Comment by watson13j** [comment]
Based on this: https://api.slack.com/methods/channels.replies

**Comment by arkie** [comment]
It looks like <https://api.slack.com/methods/channels.replies> is deprecated, and as noted on <https://github.com/arkie/dicebot/pull/62>, Slack isn't supporting commands in threads (or possibly in general, going forward? 😶)
